<?php

declare( strict_types = 1 );

namespace MediaWiki\Skin\Cosmos\Legacy;

/**
 * Old Cosmos class names mapped to their skin-cosmos- counterpart.
 */
final class LegacySelectors {

	public const array CLASSES = [
		'articleProposals' => 'skin-cosmos-article-proposals',
		'contributions-details' => 'skin-cosmos-profile__tally',
		'cosmos-actions-edit' => 'skin-cosmos-button--edit',
		'cosmos-articleAligned' => 'skin-cosmos-article-aligned',
		'cosmos-articleContainer' => 'skin-cosmos-article-container',
		'cosmos-banner-search' => 'skin-cosmos-banner__search',
		'cosmos-bannerOption' => 'skin-cosmos-banner-option',
		'cosmos-bannerOption-button' => 'skin-cosmos-banner-option__button',
		'cosmos-bannerOption-dropdownIcon' => 'skin-cosmos-banner-option__dropdown-icon',
		'cosmos-bannerOption-icon' => 'skin-cosmos-banner-option__icon',
		'cosmos-button' => 'skin-cosmos-button',
		'cosmos-button-action' => 'skin-cosmos-button--action',
		'cosmos-button-icon' => 'skin-cosmos-button__icon',
		'cosmos-button-primary' => 'skin-cosmos-button--primary',
		'cosmos-button-secondary' => 'skin-cosmos-button--secondary',
		'cosmos-button-text' => 'skin-cosmos-button__text',
		'cosmos-dashboard-icon-line' => 'skin-cosmos-dashboard-icon-line',
		'cosmos-dropdown' => 'skin-cosmos-dropdown',
		'cosmos-dropdown-button' => 'skin-cosmos-dropdown__button',
		'cosmos-dropdown-icon' => 'skin-cosmos-dropdown__icon',
		'cosmos-dropdown-list' => 'skin-cosmos-dropdown__list',
		'cosmos-emptyListMessage' => 'skin-cosmos-empty-list-message',
		'cosmos-footerIcons-listItem' => 'skin-cosmos-footer__icons-item',
		'cosmos-footerLinks-list' => 'skin-cosmos-footer__links',
		'cosmos-footerLinks-listItem' => 'skin-cosmos-footer__links-item',
		'cosmos-header' => 'skin-cosmos-header',
		'cosmos-header__counter' => 'skin-cosmos-header__counter',
		'cosmos-header__counter-label' => 'skin-cosmos-header__counter-label',
		'cosmos-header__counter-value' => 'skin-cosmos-header__counter-value',
		'cosmos-header__local-navigation' => 'skin-cosmos-header__navigation',
		'cosmos-header__sitename' => 'skin-cosmos-header__sitename',
		'cosmos-header__top-container' => 'skin-cosmos-header__top',
		'cosmos-header__wiki-buttons' => 'skin-cosmos-header__buttons',
		'cosmos-header__wordmark' => 'skin-cosmos-header__wordmark',
		'cosmos-mobile-menu-button' => 'skin-cosmos-mobile-menu__button',
		'cosmos-mobile-navigation' => 'skin-cosmos-mobile-menu',
		'cosmos-modal' => 'skin-cosmos-modal',
		'cosmos-modal-content' => 'skin-cosmos-modal__content',
		'cosmos-notifications-numNotifs' => 'skin-cosmos-notifications__count',
		'cosmos-pageAligned' => 'skin-cosmos-page-aligned',
		'cosmos-personalTools-list' => 'skin-cosmos-personal-tools__list',
		'cosmos-rail-inner' => 'skin-cosmos-rail__inner',
		'cosmos-recentChanges-info' => 'skin-cosmos-recent-changes__info',
		'cosmos-recentChanges-page' => 'skin-cosmos-recent-changes__page',
		'cosmos-search-box' => 'skin-cosmos-search-box',
		'cosmos-search-box-form' => 'skin-cosmos-search-box__form',
		'cosmos-search-button' => 'skin-cosmos-search-box__button',
		'cosmos-search-input' => 'skin-cosmos-search-box__input',
		'cosmos-sidebarAligned' => 'skin-cosmos-sidebar-aligned',
		'cosmos-toolbar-tools' => 'skin-cosmos-toolbar__tools',
		'cosmos-tools-list' => 'skin-cosmos-toolbar__list',
		'cosmos-typeahead-search' => 'skin-cosmos-typeahead-search',
		'cosmos-userButton-label' => 'skin-cosmos-personal-tools__user-label',
		'cosmos-userOptions-personalTools' => 'skin-cosmos-personal-tools',
		'CosmosRail' => 'skin-cosmos-rail',
		'create-page-dialog__button' => 'skin-cosmos-create-dialog__button',
		'create-page-dialog__close' => 'skin-cosmos-create-dialog__close',
		'create-page-dialog__proposals' => 'skin-cosmos-create-dialog__proposals',
		'create-page-dialog__title-wrapper' => 'skin-cosmos-create-dialog__title',
		'create-page-dialog__wrapper' => 'skin-cosmos-create-dialog',
		'mainpage' => 'skin-cosmos-is-main-page',
		'page-header__categories' => 'skin-cosmos-categories',
		'page-header__categories-dropdown' => 'skin-cosmos-categories__menu',
		'page-header__categories-dropdown-content' => 'skin-cosmos-categories__menu-content',
		'page-header__categories-in' => 'skin-cosmos-categories__label',
		'page-header__categories-links' => 'skin-cosmos-categories__links',
		'page-header__languages' => 'skin-cosmos-languages',
		'page-header__variants' => 'skin-cosmos-variants',
		'previewnote' => 'skin-cosmos-navigation-preview__note',
		'rail-sticky-module' => 'skin-cosmos-rail__module--sticky',
		'railModule' => 'skin-cosmos-rail__module',
		'search-form__loader' => 'skin-cosmos-search-form__loader',
		'tag-blocked' => 'skin-cosmos-profile__tag--blocked',
		'theme-dark' => 'skin-cosmos-theme-dark',
		'theme-light' => 'skin-cosmos-theme-light',
		'ts-container' => 'skin-cosmos-container',
		'ts-inner' => 'skin-cosmos-container__inner',
		'user-anon' => 'skin-cosmos-user-anon',
		'user-language' => 'skin-cosmos-interlang__language',
		'user-logged' => 'skin-cosmos-user-logged',
		'user-variant' => 'skin-cosmos-interlang__variant',
		'variant-link' => 'skin-cosmos-interlang__variant-link',
		'wds-button' => 'skin-cosmos-header__button',
		'wds-button-group' => 'skin-cosmos-header__buttons',
		'wds-dialog__actions' => 'skin-cosmos-dialog__actions',
		'wds-dialog__content' => 'skin-cosmos-dialog__content',
		'wds-dialog__title' => 'skin-cosmos-dialog__title',
		'wds-dialog__wrapper' => 'skin-cosmos-dialog',
		'wds-dropdown' => 'skin-cosmos-menu',
		'wds-dropdown-chevron' => 'skin-cosmos-submenu__chevron',
		'wds-dropdown-level-2' => 'skin-cosmos-submenu',
		'wds-dropdown-level-2__content' => 'skin-cosmos-submenu__content',
		'wds-dropdown-level-2__toggle' => 'skin-cosmos-submenu__toggle',
		'wds-dropdown__content' => 'skin-cosmos-menu__content',
		'wds-dropdown__toggle' => 'skin-cosmos-menu__toggle',
		'wds-dropdown__toggle-chevron' => 'skin-cosmos-menu__chevron',
		'wds-has-bolded-items' => 'skin-cosmos-list--bold',
		'wds-input' => 'skin-cosmos-field',
		'wds-input__field' => 'skin-cosmos-field__input',
		'wds-is-left-aligned' => 'skin-cosmos-is-left',
		'wds-is-linked' => 'skin-cosmos-list--linked',
		'wds-is-not-scrollable' => 'skin-cosmos-is-unscrollable',
		'wds-is-right-aligned' => 'skin-cosmos-is-right',
		'wds-is-secondary' => 'skin-cosmos-is-secondary',
		'wds-is-sticked-to-parent' => 'skin-cosmos-is-attached',
		'wds-is-text' => 'skin-cosmos-is-text',
		'wds-list' => 'skin-cosmos-list',
		'wds-tabs' => 'skin-cosmos-nav',
		'wds-tabs__tab' => 'skin-cosmos-nav__item',
		'wds-tabs__tab-label' => 'skin-cosmos-nav__label',
	];

	public const array IDS = [
		'wds-icons-activity-small' => 'skin-cosmos-header__icon--recent-changes',
		'wds-icons-dashboard-small' => 'skin-cosmos-header__icon--admin',
		'wds-icons-dropdown-tiny' => 'skin-cosmos-menu__chevron',
		'wds-icons-menu-control-tiny' => 'skin-cosmos-submenu__chevron',
		'wds-icons-more' => 'skin-cosmos-header__icon--more',
		'wds-icons-page-small' => 'skin-cosmos-header__icon--create',
	];

	/** Old SVG icon classes which no longer match anything meaningful. */
	public const array ICON_CLASSES = [
		'wds-icon',
		'wds-icon-medium',
		'wds-icon-small',
		'wds-icon-tiny',
	];
}
