-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE cosmos_theme (
  cth_id SERIAL NOT NULL,
  cth_timestamp TIMESTAMPTZ NOT NULL,
  cth_actor BIGINT NOT NULL,
  cth_comment TEXT DEFAULT '' NOT NULL,
  cth_version SMALLINT DEFAULT 1 NOT NULL,
  cth_hash TEXT NOT NULL,
  cth_data TEXT NOT NULL,
  PRIMARY KEY(cth_id)
);

CREATE INDEX cth_timestamp ON cosmos_theme (cth_timestamp);

CREATE INDEX cth_actor ON cosmos_theme (cth_actor);
