-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cosmos_theme (
  cth_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  cth_timestamp BLOB NOT NULL,
  cth_actor BIGINT UNSIGNED NOT NULL,
  cth_comment BLOB DEFAULT '' NOT NULL,
  cth_version SMALLINT UNSIGNED DEFAULT 1 NOT NULL,
  cth_hash BLOB NOT NULL,
  cth_data BLOB NOT NULL
);

CREATE INDEX cth_timestamp ON /*_*/cosmos_theme (cth_timestamp);

CREATE INDEX cth_actor ON /*_*/cosmos_theme (cth_actor);
