-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/cosmos_theme (
  cth_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  cth_timestamp BINARY(14) NOT NULL,
  cth_actor BIGINT UNSIGNED NOT NULL,
  cth_comment VARBINARY(767) DEFAULT '' NOT NULL,
  cth_version SMALLINT UNSIGNED DEFAULT 1 NOT NULL,
  cth_hash VARBINARY(40) NOT NULL,
  cth_data MEDIUMBLOB NOT NULL,
  INDEX cth_timestamp (cth_timestamp),
  INDEX cth_actor (cth_actor),
  PRIMARY KEY(cth_id)
) /*$wgDBTableOptions*/;
